spring.mvc.static-path-pattern=/static/**

springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


spring.boot.admin.client.url=http://localhost:8888 

spring.info.author.name=Srivatsan
spring.info.description=This is a sample Spring Boot application to demonstrate Spring Boot Admin features.
management.info.env.enabled=true